# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce78b8f3a5e951b9ccd6278c15bfac8a6dfb581a56bcdb079a97f516ae13e019ab7b76ef2ff2dd3486cbb438ea83f9fd7f2771517f0928a8745ad1e3dbdb2fdb

test:
  secret_key_base: 138fddfcdf37585fa2efec953be94f38c01f92aef18d333efa412ad9c50ac5afd6e94a09e84e5ca79c182916c177226ee6d7659cddce26e1d8c424ec559d43c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
